spring.application.name=employee-api
spring.datasource.url=jdbc:postgresql://localhost:5432/staff_management
spring.datasource.username=postgres
spring.datasource.password=davidmocan555
spring.datasource.driver-class-name=org.postgresql.Driver
# Show SQL statements
spring.jpa.show-sql=true
# Show values being passed to prepared statements
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE
# Root level (optional, ensures INFO logs appear)
logging.level.root=INFO

# Enable INFO for your salary package
logging.level.com.example.employee_api.salary=INFO